service: imdb-scraper
custom:
  bucketName: imdb-data
  serverless-layers:
    layersDeploymentBucket: ${self:custom.bucketName}

provider:
  name: aws
  stage: dev
  
  iam:
    role:
      name: ${sls:stage}-${self:service}
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource: 'arn:aws:s3:::${self:custom.bucketName}/*'
        - Effect: 'Allow'
          Action:
            - 'cloudwatch:PutMetricData'
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
          Resource: '*'

plugins:
  - serverless-layers

functions:
  imbd_scraper:
    handler: imbd_scraper.handler
    name: ${sls:stage}-${self:service}-function
    description: Scrape movies from IMDB website
    runtime: python3.7
    timeout: 15
    memorySize: 128

    events:
      - eventBridge:
          schedule: cron(0 0 1 * ? *)  # cron: min,hour,dayofmonth,month,dayofweek,year
          input:
            environment: ${sls:stage}
            bucket_name: ${self:custom.bucketName}
          tags:
            environment: ${sls:stage}
            name: ${self:service}-schedule

    tags:
      environment: ${sls:stage}
      name: ${self:service}-function
